/*
 * This Java source file was generated by the Gradle 'init' task.
 */
import org.junit.Test;
import static org.junit.Assert.*;
import newsApi.newsApiClient.NewsApiClient;
import newsApi.newsSource.NewsSource;
import java.util.HashMap;
import java.io.IOException;
import java.util.Collection;

public class LibraryTest {
    @Test public void testSomeLibraryMethod() {
        NewsApiClient client = new NewsApiClient("abc");
        try {
            for(NewsSource source : client.getSources(new HashMap<String, String>())) {
                System.out.println(source.toString());
            }
        } catch(IOException e) {
            return;
        } catch(Exception e) {
            e.printStackTrace();
        }
    }
}
