/*
 * This Java source file was generated by the Gradle 'init' task.
 */
import org.junit.Test;

import newsApi.newsApiClient.Category;
import newsApi.newsApiClient.Country;
import newsApi.newsApiClient.GetSourcesRequest;
import newsApi.newsApiClient.NewsSource;
import newsApi.newsApiClient.GetArticlesRequest;
import static org.junit.Assert.*;
import newsApi.newsApiClient.Article;
import java.io.IOException;
import java.util.Collection;

public class LibraryTest {
    @Test public void testGetSources() {
        Collection<NewsSource> sources;
        GetSourcesRequest req = new GetSourcesRequest.Builder().category(Category.TECHNOLOGY).build();
        try {
            sources = req.execute();
            for(NewsSource source : sources) {
                System.out.println(source.toString());
            }
        } catch(IOException e) {
            return;
        }
    }

    @Test
    public void testGetArticles() {
        GetSourcesRequest reqOne = new GetSourcesRequest.Builder().category(Category.TECHNOLOGY).build();
        NewsSource source;
        try {
            source = (NewsSource) reqOne.execute().toArray()[0];
        } catch(IOException e) {
            return;
        }
        Collection<Article> articles;
        String key = "7207b9a25f2c4f79856d5d2caf4bd1b6";
        GetArticlesRequest req = new GetArticlesRequest.Builder(key, source).build();
        try {
            articles = req.execute();
            for(Article a : articles) {
                System.out.println(a.toString());
            }
        } catch(IOException e) {
            return;
        }
    } 

}
